// <auto-generated />
using System;
using CadastroWebApi.Data.SqlServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroWebApi.Data.SqlServer.Migrations
{
    [DbContext(typeof(CadastroWebApiContext))]
    partial class CadastroWebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroWebApi.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("IdEndereco")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<Guid?>("IdPessoa");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("CadastroWebApi.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("CadastroWebApi.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("IdTelefone")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdPessoa");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdTelefone");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("CadastroWebApi.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("CadastroWebApi.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Endereco")
                        .HasForeignKey("IdPessoa");
                });

            modelBuilder.Entity("CadastroWebApi.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("CadastroWebApi.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Telefone")
                        .HasForeignKey("IdPessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
